"""
NewTestingAnurag
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
import pendulum


default_args={
    "owner": "dolece9181@adstam.com,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-04-22", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "dolece9181@adstam.com": "mailto:dolece9181@adstam.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clul8ja4c01q201kwopb4u18u/cloud-ide/clul8ntr201t301ivb2a8z64z/clvat14lf03ks01nckpkbiced",
    },
)
def NewTestingAnurag():

dag_obj = NewTestingAnurag()
